#!/bin/bash
# Sets up teams (tenants) and models in LiteLLM from config.json
# Admin creates everything - teams don't need to self-register models
# Run this after LiteLLM is up and healthy

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="${CONFIG_FILE:-$PROJECT_DIR/config.json}"

LITELLM_URL="${LITELLM_URL:-http://localhost:4000}"
MASTER_KEY="${LITELLM_MASTER_KEY:-sk-master-key-change-me}"

echo "=============================================="
echo "LiteLLM Multi-Tenant Setup (Admin Mode)"
echo "=============================================="
echo "URL: $LITELLM_URL"
echo "Config: $CONFIG_FILE"
echo ""

# Check config file exists
if [ ! -f "$CONFIG_FILE" ]; then
  echo "ERROR: Config file not found: $CONFIG_FILE"
  echo ""
  echo "Create one by copying the sample:"
  echo "  cp config.sample.json config.json"
  echo ""
  exit 1
fi

# Validate JSON
if ! jq empty "$CONFIG_FILE" 2>/dev/null; then
  echo "ERROR: Invalid JSON in $CONFIG_FILE"
  exit 1
fi

# Wait for LiteLLM to be ready
echo "Waiting for LiteLLM to be ready..."
until curl -s "$LITELLM_URL/health" > /dev/null 2>&1; do
  sleep 2
  echo "  ...waiting"
done
echo "LiteLLM is ready!"
echo ""

# ============================================
# STEP 1: Register Models (Admin)
# ============================================
echo "=============================================="
echo "STEP 1: Admin Registering Models"
echo "=============================================="

MODEL_COUNT=$(jq '.models | length' "$CONFIG_FILE")
echo "Found $MODEL_COUNT models in config"

for i in $(seq 0 $((MODEL_COUNT - 1))); do
  MODEL_NAME=$(jq -r ".models[$i].name" "$CONFIG_FILE")
  echo ""
  echo "Registering model: $MODEL_NAME"

  # Build the request payload
  PAYLOAD=$(jq -c "{
    model_name: .models[$i].name,
    litellm_params: .models[$i].litellm_params,
    model_info: .models[$i].model_info
  }" "$CONFIG_FILE")

  RESPONSE=$(curl -s -X POST "$LITELLM_URL/model/new" \
    -H "Authorization: Bearer $MASTER_KEY" \
    -H "Content-Type: application/json" \
    -d "$PAYLOAD")

  if echo "$RESPONSE" | jq -e '.error' > /dev/null 2>&1; then
    echo "  ERROR: $(echo "$RESPONSE" | jq -r '.error.message')"
  else
    MODEL_ID=$(echo "$RESPONSE" | jq -r '.model_id')
    echo "  Created: $MODEL_ID"
  fi
done

# ============================================
# STEP 2: Create Teams
# ============================================
echo ""
echo "=============================================="
echo "STEP 2: Creating Teams"
echo "=============================================="

TEAM_COUNT=$(jq '.teams | length' "$CONFIG_FILE")
echo "Found $TEAM_COUNT teams in config"

# Arrays to store team info for key generation
declare -a TEAM_IDS
declare -a TEAM_ALIASES
declare -a TEAM_MODELS

for i in $(seq 0 $((TEAM_COUNT - 1))); do
  TEAM_ALIAS=$(jq -r ".teams[$i].alias" "$CONFIG_FILE")
  TEAM_MODELS_JSON=$(jq -c ".teams[$i].models" "$CONFIG_FILE")

  echo ""
  echo "Creating team: $TEAM_ALIAS"
  echo "  Models: $TEAM_MODELS_JSON"

  PAYLOAD=$(jq -c "{
    team_alias: .teams[$i].alias,
    models: .teams[$i].models,
    metadata: .teams[$i].metadata
  }" "$CONFIG_FILE")

  RESPONSE=$(curl -s -X POST "$LITELLM_URL/team/new" \
    -H "Authorization: Bearer $MASTER_KEY" \
    -H "Content-Type: application/json" \
    -d "$PAYLOAD")

  if echo "$RESPONSE" | jq -e '.error' > /dev/null 2>&1; then
    echo "  ERROR: $(echo "$RESPONSE" | jq -r '.error.message')"
  else
    TEAM_ID=$(echo "$RESPONSE" | jq -r '.team_id')
    echo "  Created: $TEAM_ID"

    TEAM_IDS+=("$TEAM_ID")
    TEAM_ALIASES+=("$TEAM_ALIAS")
    TEAM_MODELS+=("$TEAM_MODELS_JSON")
  fi
done

# ============================================
# STEP 3: Create Virtual Keys for Teams
# ============================================
echo ""
echo "=============================================="
echo "STEP 3: Creating Virtual Keys"
echo "=============================================="

# Clear and prepare keys file
KEYS_FILE="/tmp/litellm-keys.env"
echo "# Generated by setup-teams.sh on $(date)" > "$KEYS_FILE"
echo "" >> "$KEYS_FILE"

for i in "${!TEAM_IDS[@]}"; do
  TEAM_ID="${TEAM_IDS[$i]}"
  TEAM_ALIAS="${TEAM_ALIASES[$i]}"
  TEAM_MODELS_JSON="${TEAM_MODELS[$i]}"

  echo ""
  echo "Creating virtual key for team: $TEAM_ALIAS"

  PAYLOAD=$(cat <<EOF
{"team_id": "$TEAM_ID", "key_alias": "$TEAM_ALIAS-key", "models": $TEAM_MODELS_JSON}
EOF
)

  RESPONSE=$(curl -s -X POST "$LITELLM_URL/key/generate" \
    -H "Authorization: Bearer $MASTER_KEY" \
    -H "Content-Type: application/json" \
    -d "$PAYLOAD")

  if echo "$RESPONSE" | jq -e '.error' > /dev/null 2>&1; then
    echo "  ERROR: $(echo "$RESPONSE" | jq -r '.error.message')"
  else
    KEY=$(echo "$RESPONSE" | jq -r '.key')
    echo "  Key: $KEY"

    # Save to env file (convert alias to uppercase variable name)
    VAR_NAME=$(echo "${TEAM_ALIAS}" | tr '[:lower:]-' '[:upper:]_')
    # Get first model for this team
    FIRST_MODEL=$(echo "$TEAM_MODELS_JSON" | jq -r '.[0]')
    echo "# Team: $TEAM_ALIAS" >> "$KEYS_FILE"
    echo "${VAR_NAME}_TEAM_ID=$TEAM_ID" >> "$KEYS_FILE"
    echo "${VAR_NAME}_KEY=$KEY" >> "$KEYS_FILE"
    echo "${VAR_NAME}_MODEL=$FIRST_MODEL" >> "$KEYS_FILE"
    echo "" >> "$KEYS_FILE"
  fi
done

# ============================================
# SUMMARY
# ============================================
echo ""
echo "=============================================="
echo "SETUP COMPLETE"
echo "=============================================="
echo ""
echo "Keys saved to $KEYS_FILE"
echo ""
echo "To use the keys:"
echo "  source $KEYS_FILE"
echo ""
echo "Then test with:"
echo "  curl $LITELLM_URL/v1/chat/completions \\"
echo "    -H \"Authorization: Bearer \$ACME_CORP_KEY\" \\"
echo "    -H \"Content-Type: application/json\" \\"
echo "    -d '{\"model\": \"'\$ACME_CORP_MODEL'\", \"messages\": [{\"role\": \"user\", \"content\": \"Hello!\"}]}'"
echo ""
